### PR TITLE
Drop the init container

### PR DESCRIPTION
**Pull request by fao89**
[OSPRH-10266](https://issues.redhat.com//browse/OSPRH-10266)

### CODE REVIEW

**Comment by bshephar** [comment]
Building and testing this one now. I'll report back

**Comment by bshephar** [comment]
Nice one, lgtm:
```
[m3@osp-df-3 beta]$ oc get po -l service=heat
NAME                           READY   STATUS        RESTARTS   AGE
heat-api-58c6f9f5d5-ct2jl      1/1     Running       0          40s
heat-api-976c7cf5d-dllvf       1/1     Terminating   0          51s
heat-cfnapi-5dbdd5cb78-w67q8   1/1     Running       0          40s
heat-engine-59f444f685-4d2c9   1/1     Running       0          51s
[m3@osp-df-3 beta]$ oc get heat
NAME   STATUS   MESSAGE
heat   True     Setup complete
```

**Review by bshephar — APPROVED** [review]

**Comment by fao89** [comment]
just rebased to fix the conflicts

**Pull request merged**
